version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    networks:
      - adminer-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - CORS_ORIGIN=http://localhost
    volumes:
      - ./backend/.env:/app/.env
      - ./logs:/app/logs
    networks:
      - adminer-network
    restart: unless-stopped

  # Optional: MySQL database
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=adminer_db
      - MYSQL_USER=adminer_user
      - MYSQL_PASSWORD=adminer_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - adminer-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Optional: PostgreSQL database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=adminer_db
      - POSTGRES_USER=adminer_user
      - POSTGRES_PASSWORD=adminer_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adminer-network
    restart: unless-stopped

volumes:
  mysql_data:
  postgres_data:

networks:
  adminer-network:
    driver: bridge
